travis:
  secure:
    BINSTAR_TOKEN: rY42NwzEkt1SLo96mRXq/GknkZFhlNuR4JdyDo2DiL+09ykMSQZ7wlknl1ngrl0m2I+bSYpIMNtsNn5riH0UgQSMFDmjluCVIllnS/1VYLKtoEgN4epdeOOEPEOEtZdqu0x+lHzNXrLha+73QvyUhxgAc+5K/Cz6q5ydGIkOoFLdaY8lbXDpf1U5d269m+noq2QiZGXaGG1qX7KRIEKKj04zgAlNOJZ3VseRjQ8HiRAlR9bVqLFMbDDzXJxeDR9IBlJuuEVE42gYvmcKPjDS/BfOZfT+2n0yDEkno1nM0KHmOOu7phgo1xMFLmYmmLfq2Duro0tVB7FIs6ynqJwRfCJjogKcwbS/jKVH6OhvY0QWslbiIke5kPk1BWI/wJOb8+p0J29C+7PXul85PylsjVQvsqs8y6HymTedGGtR7M1DvmOZ70njuqqN7zKGpIh9xtHliigao+qAA7fK+KsNqOARjZWLpWSwVNb4oIjYlCOjfar285eA7rWFgFDuasFj3art2Q41GYzFSN40iSs8JGx8IoFOOypCU6H8v+aJuEp2Ip6bgH9y8mgESBXZmT/TpnidmWJoB78F+2SB9LtEn+6FJfcvY3IQslc/PIP01Sy2la/Z36RVicooCgnAFufa0Xzulb5hJxOoZUbzMJVtvrT/ss+knyoR2/JA/0PACWg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
